services:
  backend:
    image: ericjakovac/warehouse-backend:1.2
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://aws-0-eu-central-2.pooler.supabase.com:6543/postgres?user=postgres.ltnadadrqhwenjlzdvqc&password=password
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
    expose:
      - "8080"
    networks:
      - warehouse-network
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure

  frontend-nginx:
    image: ericjakovac/warehouse-frontend-nginx:1.2
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - warehouse-network

networks:
  warehouse-network:
    driver: overlay
